version: "3"

services:
  mongodb:
    container_name: mongodb
    restart: always
    build: ./mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongodb/:/docker-entrypoint-initdb.d/
      - mongo-volume:/data/db

volumes:
  mongo-volume:
