version: "3"

services:
  # nginx:
  #   container_name: nginx
  #   restart: always
  #   build: ./nginx
  #   ports:
  #     - target: 6001
  #       published: 6001
  #       mode: host
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
  #   networks:
  #     - web_network

  # backend:
  #   container_name: acy_backend
  #   restart: always
  #   build: .
  #   expose:
  #     - "3001"
  #   depends_on:
  #     - mongodb
  #   volumes:
  #     - ./src:/code/src
  #     - ./node_modules:/code/node_modules
  #     - ./public:/code/public
  #     - .env:/code/.env
  #   networks:
  #     - web_network
  #     - db_network
  #   command: npm run deploy

  mongodb:
    container_name: mongodb
    restart: always
    build: ./mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongodb/:/docker-entrypoint-initdb.d/
      - mongo-volume:/data/db
    networks:
      - db_network

volumes:
  mongo-volume:

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge
